name: Backend CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: npm run build --if-present

      - name: Run tests
        run: npm test || true   # avoid blocking deploy if no tests

      - name: Deploy on EC2 with PM2
        run: |
          cd ~/backend
          git fetch --all
          git reset --hard origin/main
          npm install --production
          pm2 restart backend || pm2 start ecosystem.config.js --env production
          pm2 save
